// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/5/2026, 10:12:09 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/damian/Desktop/chalkstudio/chalkstudio/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/damian/Desktop/chalkstudio/chalkstudio/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/damian/Desktop/chalkstudio/chalkstudio/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/damian/Desktop/chalkstudio/chalkstudio/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/damian/Desktop/chalkstudio/chalkstudio/app/plugins/**/*.{js,ts,mjs}","/home/damian/Desktop/chalkstudio/chalkstudio/app/composables/**/*.{js,ts,mjs}","/home/damian/Desktop/chalkstudio/chalkstudio/app/utils/**/*.{js,ts,mjs}","/home/damian/Desktop/chalkstudio/chalkstudio/app/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/damian/Desktop/chalkstudio/chalkstudio/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/damian/Desktop/chalkstudio/chalkstudio/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/damian/Desktop/chalkstudio/chalkstudio/app/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;